# Generated by Django 4.2.24 on 2025-09-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, verbose_name='ism-familya')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='telegram username')),
                ('telegram_id', models.BigIntegerField(default=1, unique=True, verbose_name='telegram ID')),
                ('locatsiya_lat', models.BigIntegerField(verbose_name='loc. latude')),
                ('locatsiya_long', models.BigIntegerField(verbose_name='loc. langtude')),
                ('number', models.BigIntegerField(verbose_name='telefon raqam')),
            ],
        ),
    ]
