# Generated by Django 4.2.24 on 2025-09-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijozlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locatsiya_lat',
            field=models.BigIntegerField(null=True, verbose_name='loc. latude'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locatsiya_long',
            field=models.BigIntegerField(null=True, verbose_name='loc. langtude'),
        ),
    ]
